export const keyMenuOptionsByKey = {
	A: "(to be updated)",
	B: "(to be updated)",
	C: "(to be updated)",
	D: "(to be updated)",
	E: "(to be updated)",
	F: "(to be updated)",
	G: "(to be updated)",
	H: "(to be updated)",
	I: "(to be updated)",
	J: "(to be updated)",
	M: "(to be updated)",
	P: "(to be updated)",
	R: "(to be updated)",
	T: "(to be updated)",
	U: "(to be updated)",
	V: "(to be updated)",
	W: "(to be updated)",
	Y: "(to be updated)",
	Z: "(to be updated)",
};
