import { Cyclable } from "./Cyclable";
import { version } from "./version";
import { noop } from "./misc";

export const Nimbus = {
	version,
	logString: "",
	autoCompleteInputComponent: {
		matches: [],
		currentIndex: -1,
		commands: [],
		commandsByShortCode: {},
		shortCodes: [],
	},
	highlightTagName: "mark",
	highlightTagNameList: ["mark", "markyellow", "markpurple", "markgreen", "markblue", "markred", "markwhite"],
	smallImageThreshold: 50,
	smallImageThresholdList: [100, 200, 300, 400, 500, 600],
	trHighlightClass: {
		"mark": "trMark",
		"markyellow": "trMarkYellow",
		"markred": "trMarkRed",
		"markgreen": "trMarkGreen",
		"markblue": "trMarkBlue",
		"markpurple": "trMarkPurple",
		"markwhite": "trMarkWhite",
	},
	replacementTagName1: "h2",
	replacementTagName2: "h3",
	markerClass: "markd",
	minPersistSize: 800,
	HEADING_CONTAINER_TAGNAME: "documentheading",
	selectionHighlightMode: "sentence",
	GROUP_TAGNAME: "blockquote",
	italicTag: "i",
	logColors: {
		black: "background: #000; color: #AAA;",
		gray: "background: #555; color: #AAA;",
		blue: "background: #008; color: #ACE;",
		yellow: "background: #000; color: #CC0;",
		orange: "background: #420; color: #C80;",
		green: "background: #040; color: #0C0;",
		red: "background: #600; color: #C00;",
		purple: "background: #204; color: #C7E;",
		success: "background: #030; color: #0a0;",
		info: "background: #000; color: #aaa;",
		warning: "background: #420; color: #C70;",
		error: "background: #400; color: #a00;",
	},
	logStyles: {
		styleHeading: "font-size: 22px;",
	},
	identifyClass: {
		style: "{ box-shadow: inset 2px 2px #09C, inset -2px -2px #09C; }",
		classes: new Cyclable([]),
		markedClasses: [],
	},
	goToNextElement: {
		selector: null,
		elements: [],
		currentElement: null,
	},
	symbolsString: "∆∑σ√∫αβγλμνπΦϕΨψρστυ≃°θΩω⁰¹²³⁴⁵⁶⁷⁸⁹₀₁₂₃₄₅₆₇₈₉—",
	moduleConfigs: {
		highlightMapper: {
			width: 300,
			rowHeight: 3,
			rowSpacing: 0,
			minWidth: 3,
			groupSize: 1,
			canvasId: "highlightMapCanvas",
			maxRows: 100,
			padding: 20,
			drawGaps: false,
			elements: [],
			colorsByHighlightType: {
				plaintext: "#303030",
				currentLocation: "#A0A0A0",
				mark: "#777777",
				markyellow: "#CCCC00",
				markpurple: "#6600CC",
				markgreen: "#00AA00",
				markblue: "#4444DD",
				markred: "#CC0000",
				markwhite: "#E0E0E0",
			}
		},
	},
	consoleLog: noop,
	consoleWarn: noop,
	consoleError: noop,
	keyMenu: {
		isActive: false,
		shouldExitMenuModeAfterCommand: false,
		keys: [],
	},
	showKeyCodes: false,
	bestImagesData: [],
	largeImagesData: [],
};
