import { Cyclable } from "./Cyclable";
import { version } from "./version";

export const Nimbus = {
	version,
	logString: "",
	autoCompleteInputComponent: {
		matches: [],
		currentIndex: -1,
	},
	highlightTagName: "mark",
	highlightTagNameList: ["mark", "markyellow", "markpurple", "markgreen", "markblue", "markred", "markwhite"],
	smallImageThreshold: 50,
	smallImageThresholdList: [100, 200, 300, 400, 500, 600],
	trHighlightClass: {
		"mark": "trMark",
		"markyellow": "trMarkYellow",
		"markred": "trMarkRed",
		"markgreen": "trMarkGreen",
		"markblue": "trMarkBlue",
		"markpurple": "trMarkPurple",
		"markwhite": "trMarkWhite",
	},
	replacementTagName1: "h2",
	replacementTagName2: "h3",
	markerClass: "markd",
	minPersistSize: 800,
	HEADING_CONTAINER_TAGNAME: "documentheading",
	selectionHighlightMode: "sentence",
	GROUP_TAGNAME: "blockquote",
	italicTag: "i",
	logColors: {
		gray: "background: #555; color: #AAA",
		blue: "background: #008; color: #ACE",
		yellow: "background: #000; color: #CC0",
		green: "background: #040; color: #0C0",
		red: "background: #600; color: #C00",
	},
	identifyClass: {
		style: "{ box-shadow: inset 2px 2px #09C, inset -2px -2px #09C; }",
		classes: new Cyclable([]),
		markedClasses: [],
	},
	goToNextElement: {
		selector: null,
		elements: [],
		currentElement: null,
	},
	symbolsString: "∆∑σ√∫αβγλμνπΦϕΨψρστυ≃°θΩω⁰¹²³⁴⁵⁶⁷⁸⁹₀₁₂₃₄₅₆₇₈₉—",
	moduleConfigs: {
		highlightMapper: {
			width: 300,
			rowHeight: 4,
			rowSpacing: 1,
			minWidth: 4,
			groupSize: 1,
			canvasId: "highlightMapCanvas",
			maxRows: 100,
			padding: 20,
			drawGaps: false,
			elements: [],
			colorsByHighlightType: {
				plaintext: "#303030",
				currentLocation: "#A0A0A0",
				mark: "#777777",
				markyellow: "#CCCC00",
				markpurple: "#6600CC",
				markgreen: "#00AA00",
				markblue: "#4444DD",
				markred: "#CC0000",
				markwhite: "#E0E0E0",
			}
		},
	},
};
