export const Nimbus = {
	version: "",
	logString: "",
	autoCompleteInputComponent: {
		matches: [],
		currentIndex: -1,
		commands: [],
		commandsByShortCode: {},
		shortCodes: [],
	},
	highlightTagName: "mark",
	highlightTagNameList: ["mark", "markyellow", "markpurple", "markgreen", "markblue", "markred", "markwhite"],
	smallImageThreshold: 50,
	smallImageThresholdList: [100, 200, 300, 400, 500, 600],
	trHighlightClass: {
		"mark": "trMark",
		"markyellow": "trMarkYellow",
		"markred": "trMarkRed",
		"markgreen": "trMarkGreen",
		"markblue": "trMarkBlue",
		"markpurple": "trMarkPurple",
		"markwhite": "trMarkWhite",
	},
	replacementTagName1: "h2",
	replacementTagName2: "h3",
	markerClass: "markd",
	minPersistSize: 800,
	HEADING_CONTAINER_TAGNAME: "documentheading",
	selectionHighlightMode: "sentence",
	GROUP_TAGNAME: "blockquote",
	italicTag: "i",
	identifyClass: {
		style: "{ box-shadow: inset 2px 2px #09C, inset -2px -2px #09C; }",
		classes: {},
		markedClasses: [],
	},
	goToNextElement: {
		selector: null,
		elements: [],
		currentElement: null,
	},
	symbolsString: "∆∑σ√∫αβγλμνπΦϕΨψρστυ≃°θΩω⁰¹²³⁴⁵⁶⁷⁸⁹₀₁₂₃₄₅₆₇₈₉—",
	moduleConfigs: {
		highlightMapper: {
			width: 300,
			rowHeight: 3,
			rowSpacing: 0,
			minWidth: 3,
			groupSize: 1,
			canvasId: "highlightMapCanvas",
			maxRows: 100,
			padding: 20,
			drawGaps: false,
			elements: [],
			colorsByHighlightType: {
				plaintext: "#303030",
				currentLocation: "#A0A0A0",
				mark: "#777777",
				markyellow: "#CCCC00",
				markpurple: "#6600CC",
				markgreen: "#00AA00",
				markblue: "#4444DD",
				markred: "#CC0000",
				markwhite: "#E0E0E0",
			}
		},
		proximitySearch: {
			maxDistance: 6,
			highlightAllMatches: false,
		},
	},
	keyMenu: {
		isActive: false,
		shouldExitMenuModeAfterCommand: false,
		keys: [],
	},
	showKeyCodes: false,
	bestImagesData: [],
	largeImagesData: [],
};
